### ISSUE TITLE
Maybe an english translation?

### ISSUE THREAD

**Issue by Shirokamineko** [EvilTusk/MHXX-Save-Editor-on-3ds#1]
I know, it's not really an Issue, but would it be possible to make an english translation? Since some ppl of NA and even Europe are playing XX so it would be nice to have an english save editor.

**Comment by EvilTusk** [comment]
OK, I will, but I don't have any information that can be used to compare translations about palico skill.

**Comment by Shirokamineko** [comment]
That means? Should I look for something about Palico Skills?

**Comment by EvilTusk** [comment]
Well. I need the English version of Palico Skills' name.

**Comment by Shirokamineko** [comment]
https://mhxxx.kiranico.com/otskill
This should be good, right?

Btw: Great work you did there! This Editor looks good

**Comment by EvilTusk** [comment]
Thanks!  :laughing:

**Comment by Shirokamineko** [comment]
If you need help with something else, I'm here. I already tried to translate it at myself, but there are some things I can't figure out, like sentences and a few items. ^^"

Edit: Well, it even crashed so don't mind it. xD

**Comment by Shirokamineko** [comment]
I guess, this Issue can be closed since everything is clear, right?

**Comment by EvilTusk** [comment]
I might need a week to finish it.

And...what crashed?

**Comment by Shirokamineko** [comment]
When I tried to translate the Editor by myself, it just crashed. xD

And take your time, thanks for doing this. o:

**Comment by Shirokamineko** [comment]
take*

**Comment by Shirokamineko** [comment]
How is it going?

**Comment by EvilTusk** [comment]
I'm sorry, I found that the translate is too difficult, because my low level of English, so I still need to spend more time.

**Comment by Shirokamineko** [comment]
I can always help you, you just have to ask. o:

**Comment by RQV14** [comment]
I can also help if you want :)

**Comment by RQV14** [comment]
Also why not post it in gbatemp? I'm sure many of people like me are willing to help you translate it to english. :)

**Comment by EvilTusk** [comment]
The translation is over, and I have update it. 
I think there must be a lot of grammatical mistakes.  xD

**Comment by RQV14** [comment]
Nice. :)
I'll gonna try it :)

**Comment by RQV14** [comment]
I just tried it but apparently its still the same. Will you also gonna update the cia file? :)

**Comment by EvilTusk** [comment]
I'll upload it later. You can also compile it yourself by using "build.bat".

**Comment by Shirokamineko** [comment]
I tried it and everything works well, thanks for doing this, dude! ^^

**Comment by EvilTusk** [comment]
Can you give some advice on translation? :)

**Comment by RQV14** [comment]
The translation is good. If there's gonna be a later release. Hope you add some detail of the skills that has been put on. :)

**Comment by Shirokamineko** [comment]
The only thing I noticed so far is: That it's Illusion instead of Transmogification (Transmog for short), we are using this word but illusion is fine. 
And another thing:
The instructions in illusion make it sound like you're combining the whole first box with the second one. Except from these two it seems to be well, I look for more later. 

Edit: I really appreciate the translation, it's just so useful to have an Editor as CIA. ^^

**Comment by RQV14** [comment]
Can i have a request? Can you also put mega potion,flashbomb,pitfall trap,shock trap and also barrel bomb L + in the item section for your next update. Thank you :)
